// Model registry: what the picker shows. Explanations are user-facing copy —
// plain English, no node jargon. installed() is checked live against ComfyUI loaders.

export const MODELS = [
  {
    id: 'minimax-h3',
    name: 'MiniMax H3',
    family: 'h3',
    default: true,
    tagline: 'Video with its own sound.',
    explanation: 'Generates video with native stereo audio — dialogue, effects and music are created together in one pass, not dubbed on afterward. Strong at scenes where sound matters: streets, weather, talking shots, music visuals.',
    modes: ['t2v', 'i2v', 'audio'],
    resolutions: { 480: 'fast', 720: 'native', 1080: 'upscaled' },
    speeds: '4-step turbo · ~768p canvas · up to ~15s at 24fps',
    required: ['minimax_h3_fl2va_pruned_int8_convrot.safetensors'],
    install: 'hf download Comfy-Org/MiniMax-H3 --local-dir <models>',
    build: null, // wired in server from workflows/h3.mjs
  },
  {
    id: 'ltx-2-5',
    name: 'LTX-2.5',
    family: 'ltx25',
    tagline: 'Fast, cinematic, and it speaks too.',
    explanation: 'Lightricks’ speed-first cinematic model. Renders quickly even at length, keeps motion coherent across long shots, and also produces synchronized audio. The daily driver when you want good-looking results in minutes.',
    modes: ['t2v', 'i2v', 'audio'],
    resolutions: { 480: 'fast', 720: 'native', 1080: 'upscaled' },
    speeds: 'distilled 22B int8 · x2 latent upscaler to 1080p',
    required: ['ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors'],
    install: 'hf download Lightricks/LTX-2.5 --local-dir <models>',
  },
  {
    id: 'hunyuan-1-5',
    name: 'Hunyuan Video 1.5',
    family: 'hunyuan15',
    tagline: 'The sharp one — real 1080p.',
    explanation: 'Tencent’s detail-first model. It renders at 720p then runs a dedicated super-resolution pass to a true 1080p master — the only model here that reaches 1080p natively. Best for textures, faces, and anything you’ll watch full-screen.',
    modes: ['t2v', 'i2v'],
    resolutions: { 480: 'fast', 720: 'native', 1080: 'native' },
    speeds: '720p base + 1080p SR pass',
    required: ['hunyuanvideo1.5_720p_t2v_fp16.safetensors'],
    install: 'hf download Comfy-Org/HunyuanVideo_1.5_repackaged --local-dir <models>',
  },
  {
    id: 'wan-2-2',
    name: 'Wan 2.2',
    family: 'wan22',
    tagline: 'The reliable all-rounder.',
    explanation: 'Alibaba’s workhorse. Predictable motion, obedient prompts, and the most battle-tested local pipeline on this machine. Silent — pair it with music afterward if you need sound.',
    modes: ['t2v', 'i2v'],
    resolutions: { 480: 'native', 720: 'native', 1080: 'upscaled' },
    speeds: '14B fp8 dual-pass + 4-step turbo',
    required: ['wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors'],
    installed: true, // verified on this machine 2026-08-22
  },
  {
    id: 'wan-2-6',
    name: 'Wan 2.6',
    family: 'wan26',
    tagline: 'Newer, richer Wan.',
    explanation: 'The next Wan generation: better physics and prompt adherence over 2.2. Local workflows are still being upstreamed — installable now, verified pipeline lands with it.',
    modes: ['t2v', 'i2v'],
    resolutions: { 480: 'native', 720: 'native', 1080: 'upscaled' },
    speeds: '14B-class fp8 + turbo',
    required: ['wan2.6_t2v_high_noise_14B_fp8_scaled.safetensors'],
    install: 'hf download Comfy-Org/Wan_2.6_ComfyUI_repackaged --local-dir <models>',
  },
  {
    id: 'mochi-1',
    name: 'Mochi 1',
    family: 'mochi',
    tagline: 'Smooth motion specialist.',
    explanation: 'Genmo’s open model, known for unusually fluid, dreamlike motion — water, smoke, fabric, camera drifts. Lower native resolution; treat it as a style choice, not a sharpness choice.',
    modes: ['t2v'],
    resolutions: { 480: 'native', 720: 'upscaled', 1080: 'upscaled' },
    speeds: '10B asymmetric DiT',
    required: ['mochi_preview_bf16.safetensors'],
    install: 'hf download Comfy-Org/mochi_preview_repackaged --local-dir <models>',
  },
  {
    id: 'cogvideox',
    name: 'CogVideoX',
    family: 'cogvideox',
    tagline: 'Compact and instruction-precise.',
    explanation: 'Zhipu’s efficient family. Smaller footprint, tight prompt-following, good for iterative drafts and shorter clips. Text-to-video and image-to-video come from the -I2V weights.',
    modes: ['t2v', 'i2v'],
    resolutions: { 480: 'native', 720: 'upscaled', 1080: 'unavailable' },
    speeds: '2B/5B DiT',
    required: ['cogvideox_5b.safetensors'],
    install: 'hf download zai-org/CogVideoX-5b --local-dir <models>',
  },
  {
    id: 'skyreels-v1',
    name: 'SkyReels V1',
    family: 'skyreels',
    tagline: 'Film-language camera work.',
    explanation: 'Built on HunyuanVideo and trained on cinematic camera moves — it understands dolly, orbit, and crane language in the prompt. Choose it when the shot itself is the point.',
    modes: ['t2v', 'i2v'],
    resolutions: { 480: 'native', 720: 'native', 1080: 'upscaled' },
    speeds: 'Hunyuan-class 13B',
    required: ['skyreels_v1_hunyuan_t2v_bf16.safetensors'],
    install: 'hf download Kijai/SkyReels-V1-Hunyuan_comfy --local-dir <models>',
  },
];

export const DEFAULT_MODEL = 'minimax-h3';
